load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "glfw_output",
    srcs = ["glfw_output.cc"],
    copts = [
        "-std=c++20",
        "-Wall",
        "-Wextra",
        "-Wpedantic",
    ],
    linkopts = select({
        "@platforms//os:linux": ["-ldl"],
        "//conditions:default": [],
    }),
    visibility = ["//visibility:public"],
    deps = [
        "//:glfw_output_headers",
        "//libs/raster",
        "//third_party/glfw:glfw_headers",
    ],
)
