from typing import Final, Optional, Sequence

class GeometryKind: POINT: GeometryKind; POLYLINE: GeometryKind; PATCH: GeometryKind; VOLUME: GeometryKind; RAY_PATH: GeometryKind
class CoordinateSpace: WORLD: CoordinateSpace; SURFACE_LOCAL: CoordinateSpace
class Composition: OVER: Composition; REPLACE: Composition; ADD: Composition
class OutputMix: EXCLUSIVE: OutputMix; NORMALIZED: OutputMix; ADDITIVE: OutputMix
class Traversal: STABLE: Traversal; PRIORITY: Traversal; SHORTEST_PATH: Traversal
class Presentation: IMMEDIATE: Presentation; TIMED: Presentation; SYNCHRONIZED_GROUP: Presentation
class DeviceKind: FIXED_RASTER: DeviceKind; STEERABLE_RASTER: DeviceKind; GALVO: DeviceKind; UNSUPPORTED: DeviceKind
class PlanStatus: ACCEPTED: PlanStatus; UNSUPPORTED: PlanStatus; INFEASIBLE: PlanStatus; NO_PLAN_FOUND: PlanStatus; INVALIDATED: PlanStatus
class Provenance: SIMULATED: Provenance; PREDICTED: Provenance; MEASURED: Provenance; UNAVAILABLE: Provenance
class Availability: AVAILABLE: Availability; UNAVAILABLE: Availability; FAILED: Availability; HANDING_OFF: Availability
class EventKind: BLANK: EventKind; EMIT: EventKind; DWELL: EventKind; POSE: EventKind; TRIGGER: EventKind
class Plane: id: str; origin: Sequence[float]; u: Sequence[float]; v: Sequence[float]
class PlanarMotion: linear_velocity: Sequence[float]; angular_velocity: Sequence[float]
class Occluder: id: str; min: Sequence[float]; max: Sequence[float]
class WorldSnapshot: planes: list[Plane]; occluders: list[Occluder]; source_time: float; valid_until: float; world_revision: int; calibration_revision: int; motion: list[PlanarMotion]
class SurfaceTarget: surface_id: str; coordinates: CoordinateSpace; origin: Sequence[float]; vertices: list[Sequence[float]]; u: Sequence[float]; v: Sequence[float]; geometry: GeometryKind; captured_at: float; stable_path_id: str
class DrawCall: draw_id: str; target: SurfaceTarget; linear_rgb: Sequence[float]; intensity: float; priority: int; closed: bool; opacity: float
class DisplayList: id: str; app_id: str; present_at: float; expires_at: float; world_revision: int; calibration_revision: int; composition: Composition; draws: list[DrawCall]
class PipelineState: sample_spacing: float; max_position_error: float; max_samples: int; output_mix: OutputMix; allow_laser_fill_approximation: bool
class TraversalState: order: Traversal; max_dark_gap: float; minimum_duty: float
class PresentationState: mode: Presentation; requested_group_skew: float; require_sync: bool
class DeviceProfile: id: str; kind: DeviceKind; position: Sequence[float]; target: Sequence[float]; up: Sequence[float]; fov_y: float; near_plane: float; far_plane: float; width: int; height: int; sample_rate_hz: float; latency: float; clock_offset: float; clock_drift: float; clock_uncertainty: float; max_angular_speed: float; settling_time: float; max_sample_dwell: float; resource_ids: list[str]; calibrated_gain: Sequence[float]; sample_budget: int
class Resource: id: str; capacity: float
class Rig: devices: list[DeviceProfile]; resources: list[Resource]
class ProgramEvent: kind: Final[EventKind]; time: Final[float]; position: Final[Sequence[float]]; linear_rgb: Final[Sequence[float]]; dwell: Final[float]; draw_id: Final[str]; display_list_id: Final[str]; surface_id: Final[str]
class TimedProgram: device_id: Final[str]; device_kind: Final[DeviceKind]; display_list_id: Final[str]; generation: Final[int]; world_revision: Final[int]; calibration_revision: Final[int]; issued_at: Final[float]; starts_at: Final[float]; expires_at: Final[float]; events: Final[list[ProgramEvent]]
class Diagnostic: status: Final[PlanStatus]; object_id: Final[str]; code: Final[str]; message: Final[str]
class Contribution: draw_id: Final[str]; display_list_id: Final[str]; surface_id: Final[str]; device_id: Final[str]; position: Final[Sequence[float]]; linear_rgb: Final[Sequence[float]]; intensity: Final[float]; occlusion_fraction: Final[float]; duty_fraction: Final[Optional[float]]; provenance: Final[Provenance]
class TargetLight: draw_id: Final[str]; display_list_id: Final[str]; aggregate_linear_rgb: Final[Sequence[float]]; position_error: Final[Optional[float]]; age: Final[float]; duty: Final[Optional[float]]; max_dark_gap: Final[Optional[float]]; provenance: Final[Provenance]
class Receipt: device_id: Final[str]; generation: Final[int]; availability: Final[Availability]; accepted_at: Final[float]; timing_uncertainty: Final[float]; provenance: Final[Provenance]
class Snapshot: time: Final[float]; world_revision: Final[int]; calibration_revision: Final[int]; contributions: Final[list[Contribution]]; targets: Final[list[TargetLight]]; programs: Final[list[TimedProgram]]; receipts: Final[list[Receipt]]; diagnostics: Final[list[Diagnostic]]
class RuntimeOptions: pipeline: PipelineState; traversal: TraversalState; presentation: PresentationState; planner_candidate_budget: int
class OpticalRuntime:
    def __init__(self, world: WorldSnapshot, rig: Rig, options: RuntimeOptions = ...) -> None: ...
    def submit(self, display: DisplayList) -> list[Diagnostic]: ...
    def advance(self, to_time: float) -> Snapshot: ...
    def snapshot(self) -> Snapshot: ...
    def cancel(self, display_list_id: str) -> int: ...
    def set_availability(self, device_id: str, availability: Availability) -> None: ...
    def update_world(self, world: WorldSnapshot) -> None: ...
def validate_world(world: WorldSnapshot, rig: Rig, options: RuntimeOptions = ...) -> list[Diagnostic]: ...
def validate_display(display: DisplayList) -> list[Diagnostic]: ...
def fixed_raster(device_id: str, **kwargs) -> DeviceProfile: ...
def steerable_raster(device_id: str, **kwargs) -> DeviceProfile: ...
def galvo(device_id: str, **kwargs) -> DeviceProfile: ...
def world(planes: Sequence[Plane], **kwargs) -> WorldSnapshot: ...
def rig(devices: Sequence[DeviceProfile], resources: Sequence[Resource] = ...) -> Rig: ...
def plane(surface_id: str, **kwargs) -> Plane: ...
def occluder(occluder_id: str, minimum: Sequence[float], maximum: Sequence[float]) -> Occluder: ...
def draw(draw_id: str, surface_id: str, position: Sequence[float] = ..., **kwargs) -> DrawCall: ...
def display(display_id: str, draws: Sequence[DrawCall], **kwargs) -> DisplayList: ...
